// src/routes/app/permissions/index.svelte
<script lang="typescript">
	import { onMount } from 'svelte';
	import { getRoleAction, removePermissionsToRoleAction, addPermissionsToRoleAction, rolesList, isLoading as roleLoading } from '@/stores/role/roleStore';
	import {
		getPermissionAction,
		permissionsList,
		isLoading as permissionLoading
	} from '@/stores/permission/permissionStore';
	import RolePermission from '@/components/app/RolePermission.svelte';
import type { RelationsInput } from '@/shared/types/relationsInput';
import type { Permission } from '@/stores/permission/types/permission';
import type { Role } from '@/stores/role/types/role';
	let isLoading: boolean;

	onMount(() => {
		getPermissionAction();
		getRoleAction();
	});

	roleLoading.subscribe((loading) => (isLoading = loading));
	permissionLoading.subscribe((loading) => (isLoading = loading));

	const onCheck = (event) => {
		const value: {
      value: boolean;
      permission: Permission;
      role: Role;
    } = event.detail
		  const data: RelationsInput = {
		    id: value.role.id,
		    relationIds: [value.permission.id],
		  };
		  if (value.value) {
		    addPermissionsToRoleAction(data);
		  } else {
		    removePermissionsToRoleAction(data);
		  }
	};
</script>

<div>
	{#if $rolesList && $permissionsList}
		<RolePermission
			roles={$rolesList?.edges}
			permissions={$permissionsList}
			on:check={onCheck}
		/>
	{/if}
</div>

// src/views/pages/roles-permissions/Permissions.vue
<template lang="jsx">
<div>
    <RolePermission 
    v-if="permissions && roleConnection" 
    :roles="roleConnection?.edges" 
    :permissions="permissions"
    @onCheck="onCheck"
    />   
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, ComputedRef, onMounted, ref } from "vue";
import { RoleConnection } from "@/views/pages/roles/types/roleConnection";
import RolePermission from "@/components/role-permission/Main.vue";
import { useStore } from "vuex";
import { Permission } from "./types/permission";
import { RelationsInput } from "@/shared/types/relationsInput";
import { Role } from "@/views/pages/roles/types/role";
export default defineComponent({
  components: {
    RolePermission,
  },
  setup() {
    const store = useStore();
    const selectedPermission = ref(null as Permission | null);
    const errors = computed(
      () => store.state.permissions.errors || store.state.roles.errors
    );
    const loading = computed(
      () => store.state.permissions.loading || store.state.roles.loading
    );

    onMounted(() => {
      store.dispatch("permissions/getPermissionAction");
      store.dispatch("roles/getRoleAction");
    });

    const permissions: ComputedRef<Permission[]> = computed(
      () => store.state.permissions.permissions
    );
    const onCheck = (value: {
      value: boolean;
      permission: Permission;
      role: Role;
    }) => {
      console.log(value.value);
      const data: RelationsInput = {
        id: value.role.id,
        relationIds: [value.permission.id],
      };
      if (value.value) {
        store.dispatch("roles/addPermissionsToRoleAction", data);
      } else {
        store.dispatch("roles/removePermissionsToRoleAction", data);
      }
    };

    const roleConnection: ComputedRef<RoleConnection> = computed(
      () => store.state.roles.roleConnection
    );

    const createSearchFilter = (searchString: string) => [
      { name: { iLike: `%${searchString}%` } },
    ];
    const onSearch = (value: string) => {
      console.log(createSearchFilter(value));
      store.dispatch("permissions/getPermissionAction", {
        filter: createSearchFilter(value),
      });
    };

    return {
      permissions,
      onSearch,
      roleConnection,
      selectedPermission,
      errors,
      loading,
      onCheck,
    };
  },
});
</script>
