// src/components/MasterForm/InputTypes/TextInput.svelte
<script lang="typescript">
	import { createEventDispatcher } from 'svelte';

	export let label: string;
	export let name: string;
	export let value: string;
	export let masked: boolean;
	export let disabled: boolean;
	const dispatch = createEventDispatcher();

	const onChange = (event) => {
		dispatch('change', {
			field: name,
			value: event.target.value
		});
	};
</script>

<div class="text-left mb-0">
	{#if label}
		<label for={name} class="w-full form-label text-left">
			{ label }
		</label>
	{/if}
	<input
		{disabled}
		id={name}
		type={masked ? 'password' : 'text'}
		class="w-full form-control px-4 py-2 transition duration-300 input input-bordered"
		{value}
		placeholder={label}
		on:input={onChange}
	/>
</div>

// src/components/master-form/input-types/text-input/Main.vue
<template lang="jsx">
<div class="text-left mb-5">
  <label v-if="label" :for="name" class="form-label text-left">
    {{ label }}
  </label>
  <input
    :disabled="disabled"
    :id="name"
    :type="masked?'password':'text'"
    class="form-control"
    :value="value"
    :placeholder="label"
    @input="onChange"
  />
</div>
</template>
<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  props: {
    label: {
      type: String,
    },
    name: {
      type: String,
    },
    value: {
      type: String,
    },
    masked: {
      type: Boolean,
    },
    disabled: {
      type: Boolean,
    },
  },
  setup(props, context) {
    const onChange = ($evt: any) => {
      context.emit("change", { field: props.name, value: $evt.target.value });
    };
    return {
      onChange,
    };
  },
});
</script>
