// src/components/MasterForm/InputTypes/SelectInput.svelte
<script lang="typescript">
	import { createEventDispatcher } from 'svelte';

	export let label: string;
	export let name: string;
	export let value: string;
	export let numericValue: boolean = false;
	export let disabled: boolean;
	export let options: {
		value: string | number | boolean;
		label: string;
	}[];
	const dispatch = createEventDispatcher();
	const onChange = (event) => {
		dispatch('change', {
			field: name,
			value: numericValue ? Number(event.target.value) : event.target.value
		});
	};
</script>

<div class="text-left mb-5">
	{#if label}
		<label for={name} class="w-full form-label text-left">
			{label}
		</label>
	{/if}

	{#if options}
		<select
			{disabled}
			id={name}
			class="w-full form-control px-4 py-2 transition duration-300 select select-bordered"
			{value}
			placeholder={label}
			on:change={onChange}
			aria-label="Default select"
		>
			{#each options as option}
				<option value={option.value}>{option.label}</option>
			{/each}
		</select>
	{/if}
</div>

// src/components/master-form/input-types/select-input/Main.vue
<template lang="jsx">
<div class="text-left mb-5">
  <label v-if="label" :for="name" class="form-label text-left">
    {{ label }}
  </label>
  <select
  :disabled="disabled"
  :id="name"
   class="form-control form-select" 
    :value="value"
    :placeholder="label"
    @change="onChange"
    aria-label="Default select">
         <option v-for="(option, index) in options" :key="index" :value="option.value" >{{option.label}}</option>
     </select>
</div>
</template>
<script lang="ts">
import { defineComponent, PropType } from "vue";
interface Option {
  label: string;
  value: string;
}
export default defineComponent({
  props: {
    label: {
      type: String,
    },
    name: {
      type: String,
    },
    numericValue: {
      type: Boolean,
    },
    options: {
      type: Array as PropType<Option[]>,
    },
    value: {
      type: String,
    },
    disabled: {
      type: Boolean,
    },
  },
  setup(props, context) {
    const onChange = ($evt: any) => {
      context.emit("change", {
        field: props.name,
        value: props.numericValue
          ? Number($evt.target.value)
          : $evt.target.value,
      });
    };
    return {
      onChange,
    };
  },
});
</script>
