// src/components/master-form/input-types/textarea-input/Main.vue
<template lang="jsx">
<div class="text-left mb-5">
  <label v-if="label" :for="name" class="form-label text-left">
    {{ label }}
  </label>
  <textarea 
  class="form-control w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none" 
    :disabled="disabled"
    :id="name"
    :value="value"
    :placeholder="label"
    @input="onChange"
  rows="4">
  </textarea>
</div>
</template>
<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  props: {
    label: {
      type: String,
    },
    name: {
      type: String,
    },
    value: {
      type: String,
    },
    masked: {
      type: Boolean,
    },
    disabled: {
      type: Boolean,
    },
  },
  setup(props, context) {
    const onChange = ($evt: any) => {
      context.emit("change", { field: props.name, value: $evt.target.value });
    };
    return {
      onChange,
    };
  },
});
</script>

// src/components/MasterForm/InputTypes/TextAreaInput.svelte
<script lang="typescript">
import { createEventDispatcher } from "svelte";


export let label:string;
export let name:string;
export let value:string;
export let disabled:boolean;
const dispatch = createEventDispatcher();

const onChange = (event)=>dispatch('change', {
        field: name,
        value: event.detail,
      })


</script>

<div class="text-left mb-0">
    {#if label}
    
    <label for={name} class="w-full form-label text-left">
      { label }
    </label>
    {/if}
    <textarea
      disabled={disabled}
      id={name}
      class="w-full form-control px-4 py-2 transition duration-300 textarea h-24 textarea-bordered"
      value={value}
      placeholder={label}
      on:input={onChange}
    ></textarea>
  </div>
